<a href="https://colab.research.google.com/github/katy2586/katy2586/blob/main/DZ4_Kuraeva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([[1, 2, 1], [-2, 1, 1]])
b= np.array ([[3, 1], [-1, 0], [2, 4]])
c = np.array ([[-2, 2],[1, -1], [1, 2]])
f = b.T
a+2*f


array([[7, 0, 5],
       [0, 1, 9]])

In [ ]:
b = np.array ([[3, 1], [-1, 0], [2, 4]])
c = np.array ([[-2, 2], [1, -1], [1, 2]])
b+2*c

array([[-1,  5],
       [ 1, -2],
       [ 4,  8]])

In [ ]:
a = np.zeros ((8,8), dtype=int)
a [1::2, ::2] = 1
a [::2, 1::2] = 1
print (a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
np.arange (0, 1.5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4])

In [ ]:
np.arange (1, 7, 1)

array([1, 2, 3, 4, 5, 6])